// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Admin", b =>
                {
                    b.Property<string>("MaAdmin")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DuongDanAnhDaiDien")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PassHash")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("longtext");

                    b.HasKey("MaAdmin")
                        .HasName("PK__Admin__49341E385C3B7968");

                    b.HasIndex(new[] { "Email" }, "UQ__Admin__A9D10534B669324A")
                        .IsUnique();

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.BaiHoc", b =>
                {
                    b.Property<string>("MaBaiHoc")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("LinkVideo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("MaKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("MaBaiHoc")
                        .HasName("PK__BaiHoc__3F6433C22ED8055C");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("BaiHoc", null, t =>
                        {
                            t.HasTrigger("trg_BaiHoc_InsteadOfInsert");
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.ChiTietGioHang", b =>
                {
                    b.Property<string>("MaGioHang")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("MaKhoaHoc")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("NgayThem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("MaGioHang", "MaKhoaHoc")
                        .HasName("PK__ChiTietG__618F125A1577708D");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("ChiTietGioHang", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.GiaoVien", b =>
                {
                    b.Property<string>("MaGiaoVien")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DuongDanAnhDaiDien")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("GioiThieu")
                        .HasColumnType("longtext");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("MaGiaoVien")
                        .HasName("PK__GiaoVien__8D374F500F7745EB");

                    b.HasIndex(new[] { "Email" }, "UQ__GiaoVien__A9D10534256C5751")
                        .IsUnique();

                    b.ToTable("GiaoVien", null, t =>
                        {
                            t.HasTrigger("trg_GiaoVien_InsteadOfInsert");
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.GioHang", b =>
                {
                    b.Property<string>("MaGioHang")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("MaHocSinh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("MaGioHang")
                        .HasName("PK__GioHang__F5001DA370627E7B");

                    b.HasIndex("MaHocSinh");

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.HocSinh", b =>
                {
                    b.Property<string>("MaHocSinh")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DuongDanAnhDaiDien")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("NgayDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("PassHash")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("longtext");

                    b.HasKey("MaHocSinh")
                        .HasName("PK__HocSinh__90BD01E092E2175A");

                    b.HasIndex(new[] { "Email" }, "UQ__HocSinh__A9D105343901994D")
                        .IsUnique();

                    b.ToTable("HocSinh", null, t =>
                        {
                            t.HasTrigger("trg_HocSinh_InsteadOfInsert");
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.KhoaHoc", b =>
                {
                    b.Property<string>("MaKhoaHoc")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DuongDanAnhKhoaHoc")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<decimal>("GiaKhoaHoc")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("MaGiaoVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MonHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("NgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ThoiHan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(150);

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("MaKhoaHoc")
                        .HasName("PK__KhoaHoc__48F0FF98AEEE8B8F");

                    b.HasIndex("MaGiaoVien");

                    b.ToTable("KhoaHoc", null, t =>
                        {
                            t.HasTrigger("trg_KhoaHoc_InsteadOfInsert");
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.KhoaHocHocSinh", b =>
                {
                    b.Property<string>("MaKhoaHoc")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaHocSinh")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("NgayDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("MaKhoaHoc", "MaHocSinh")
                        .HasName("PK__KhoaHoc___51FB2F86ADBC7414");

                    b.HasIndex("MaHocSinh");

                    b.ToTable("KhoaHoc_HocSinh", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.MucTieuKhoaHoc", b =>
                {
                    b.Property<string>("MaKhoaHoc")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("MaKhoaHoc", "ThuTu")
                        .HasName("PK__MucTieuK__5A127CA5CA5D6BF8");

                    b.ToTable("MucTieuKhoaHoc", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.YeuCauKhoaHoc", b =>
                {
                    b.Property<string>("MaKhoaHoc")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("MaKhoaHoc", "ThuTu")
                        .HasName("PK__YeuCauKh__5A127CA5E3AEE7DB");

                    b.ToTable("YeuCauKhoaHoc", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.BaiHoc", b =>
                {
                    b.HasOne("WebApplication1.Models.KhoaHoc", "MaKhoaHocNavigation")
                        .WithMany("BaiHocs")
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BaiHoc_KhoaHoc");

                    b.Navigation("MaKhoaHocNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("WebApplication1.Models.GioHang", "MaGioHangNavigation")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaGioHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietGi__MaGio__75A278F5");

                    b.HasOne("WebApplication1.Models.KhoaHoc", "MaKhoaHocNavigation")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietGi__MaKho__76969D2E");

                    b.Navigation("MaGioHangNavigation");

                    b.Navigation("MaKhoaHocNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.GioHang", b =>
                {
                    b.HasOne("WebApplication1.Models.HocSinh", "MaHocSinhNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaHocSinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GioHang_HocSinh");

                    b.Navigation("MaHocSinhNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.KhoaHoc", b =>
                {
                    b.HasOne("WebApplication1.Models.GiaoVien", "MaGiaoVienNavigation")
                        .WithMany("KhoaHocs")
                        .HasForeignKey("MaGiaoVien")
                        .IsRequired()
                        .HasConstraintName("FK_KhoaHoc_GiaoVien");

                    b.Navigation("MaGiaoVienNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.KhoaHocHocSinh", b =>
                {
                    b.HasOne("WebApplication1.Models.HocSinh", "MaHocSinhNavigation")
                        .WithMany("KhoaHocHocSinhs")
                        .HasForeignKey("MaHocSinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KhoaHocHocSinh_HocSinh");

                    b.HasOne("WebApplication1.Models.KhoaHoc", "MaKhoaHocNavigation")
                        .WithMany("KhoaHocHocSinhs")
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KhoaHocHocSinh_KhoaHoc");

                    b.Navigation("MaHocSinhNavigation");

                    b.Navigation("MaKhoaHocNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.MucTieuKhoaHoc", b =>
                {
                    b.HasOne("WebApplication1.Models.KhoaHoc", "MaKhoaHocNavigation")
                        .WithMany("MucTieuKhoaHocs")
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__MucTieuKh__MaKho__403A8C7D");

                    b.Navigation("MaKhoaHocNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.YeuCauKhoaHoc", b =>
                {
                    b.HasOne("WebApplication1.Models.KhoaHoc", "MaKhoaHocNavigation")
                        .WithMany("YeuCauKhoaHocs")
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__YeuCauKho__MaKho__4316F928");

                    b.Navigation("MaKhoaHocNavigation");
                });

            modelBuilder.Entity("WebApplication1.Models.GiaoVien", b =>
                {
                    b.Navigation("KhoaHocs");
                });

            modelBuilder.Entity("WebApplication1.Models.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("WebApplication1.Models.HocSinh", b =>
                {
                    b.Navigation("GioHangs");

                    b.Navigation("KhoaHocHocSinhs");
                });

            modelBuilder.Entity("WebApplication1.Models.KhoaHoc", b =>
                {
                    b.Navigation("BaiHocs");

                    b.Navigation("ChiTietGioHangs");

                    b.Navigation("KhoaHocHocSinhs");

                    b.Navigation("MucTieuKhoaHocs");

                    b.Navigation("YeuCauKhoaHocs");
                });
#pragma warning restore 612, 618
        }
    }
}
